version: '3'
services:
  server:
    environment:
      - MONGO_URL=${MONGO_URL}
      - REDIS_URL=${REDIS_URL}
      - PORT=${PORT}
      - SESSION_SECRET=${SESSION_SECRET}
    build: ./server
    command: yarn nodemon index.js
    volumes:
      - ./server:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - 3001:3001
    depends_on:
      - mongo
      - redis
  client:
    build: ./client
    volumes:
      - ./client:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - 3000:3000
  mongo:
    image: mongo
    ports:
      - 27017:27017
    volumes:
      - mongo_data:/data/db
  redis:
    image: redis
    ports:
      - "6380:6379"
volumes:
  mongo_data:
